import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientWrapper from "./client-wrapper";
import Footer from "@/components/layout/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Toggle this flag to show/hide the in-progress screen
const SHOW_IN_PROGRESS = true;

export default function RootLayout({ children }) {
  if (SHOW_IN_PROGRESS) {
    return (
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}>
          <div className="relative min-h-dvh w-full bg-neutral-950 text-white">
            <div className="absolute inset-0 animated-gradient opacity-40" />
            <div className="pointer-events-none absolute -inset-x-40 -top-40 h-[60rem] rounded-[50%] bg-gradient-to-br from-lime-400/30 via-fuchsia-500/20 to-cyan-400/30 blur-3xl" />

            <div className="relative z-10 flex min-h-dvh items-center justify-center px-6">
              <section className="max-w-3xl text-center space-y-6">
                <h1 className="text-5xl md:text-7xl font-bold tracking-tight animate-fade-in-up">
                  <span className="animated-text-gradient">In progress</span>
                </h1>
                <p className="text-lg md:text-xl text-white/80 animate-fade-in-up [animation-delay:150ms]">
                  We are crafting something special. Meanwhile, reach out:
                </p>
                <div className="flex flex-col items-center gap-3 md:flex-row md:justify-center animate-fade-in-up [animation-delay:300ms]">
                  <a
                    href="mailto:valters@suntzgroup.com"
                    className="rounded-full bg-white text-neutral-900 px-6 py-3 font-medium hover:bg-lime-400 transition-colors duration-300"
                  >
                    valters@suntzgroup.com
                  </a>
                  <a
                    href="tel:+25137928"
                    className="rounded-full border border-white/30 px-6 py-3 font-medium hover:border-lime-400/70 hover:text-lime-300 transition-colors duration-300"
                  >
                    +371 25 137 928
                  </a>
                </div>
              </section>
            </div>
          </div>
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden`}
      >
        <ClientWrapper>{children}</ClientWrapper>
        <Footer />
      </body>
    </html>
  );
}
